# Generated by Django 6.0.4 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasutaja',
            name='is_activated_user',
            field=models.BooleanField(default=False),
        ),
    ]
