# Generated by Django 6.0.4 on 2026-04-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmachine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kliendivm',
            name='proxmox_username',
        ),
    ]
