# Generated by Django 6.0.4 on 2026-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmachine', '0002_remove_kliendivm_proxmox_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='kliendivm',
            name='cpu_core',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kliendivm',
            name='disk_size',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kliendivm',
            name='node',
            field=models.CharField(default='miku', max_length=255),
        ),
        migrations.AddField(
            model_name='kliendivm',
            name='ram',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kliendivm',
            name='status',
            field=models.CharField(choices=[('creating', 'Loomine'), ('running', 'Jookseb'), ('stopped', 'Peatatud'), ('error', 'Error')], default='creating', max_length=20),
        ),
    ]
