# Generated by Django 6.0.4 on 2026-05-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmachine', '0003_kliendivm_cpu_core_kliendivm_disk_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kliendivm',
            name='cpu_core',
        ),
        migrations.RemoveField(
            model_name='kliendivm',
            name='disk_size',
        ),
        migrations.RemoveField(
            model_name='kliendivm',
            name='ram',
        ),
    ]
